version: '3'
services:
  node-red-mcp:
    image: nodered/node-red:4.0.0
    container_name: node-red-mcp
    ports:
      - "1899:1880"
    volumes:    
        - ./node-red-docker/node_red_data:/data
    #Environment variables should be set dynamically via mcp-tools component
    # or via external .env file, not hardcoded here for security
    environment:
      #- ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - OPENAI_API_KEY=${OPENAI_API_KEY}   
      - ENV_MCP_VARIABLES=${ENV_MCP_VARIABLES}
      - SMITHERY_KEY=${SMITHERY_KEY}
      - SMITHERY_PROFILE=${SMITHERY_PROFILE}
    depends_on:
      - mcp-host
    networks:
      - mcp-host-network

  mcp-host:
    build:
      context: . 
      dockerfile: Dockerfile
    container_name: mcp-host
    ports:
      - "3000:3000"
    networks:
      - mcp-host-network

networks:
  mcp-host-network:
    driver: bridge
