---
version: '3'
services:
  mcp-demo:
    #build:
    #    context: .
    #    dockerfile: Dockerfile
    image: nodered/node-red:4.0.0
    container_name: mcp-demo
    ports:
      - "1899:1880"
    volumes:
        -  ./node_red_data:/data
    environment:
      ADMIN_PASSWORD: '7OhBgb4IcnJmxYJiZ73Fk.3Ht9qovXFmhVMncQ3WTT2Q9TO9WRgV6' # admin
    depends_on:
      - mcp-host
    networks:
      - mcp-network

  mcp-host:
     build:
      context: ../ # Vai criar uma imagem do mc-host o Dockerfile está na pasta do projeto
      dockerfile: Dockerfile
      #image: mcp-host  #ou mcp-host, dependendo do nome da imagem que você usou no build
     container_name: mcp-host
     ports:
      - "3000:3000"
     networks:
      - mcp-network

networks:
  mcp-network:
    driver: bridge